# -*- coding: utf-8 -*-
"""Cybersecurity Analyst Challenge(Assignment).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sgZ7ONIc2Sfb1Hud2PCojT1NMV2G-elr

I work with a gaming company with millions of user accounts. I would like to detect Account compromised, attacks and traffic spike- I have created a Synthetic dataset : My dataset will have following features

*   UserID – unique user identifier
*  Timestamp – login time
*   IP_Address – source IP
*  Country – login location
*   Device_Type – PC / Mobile / Console
*   Login_Success – Yes/No
*   Failed_Attempts – number of failed logins before success
*   Session_Duration_Min – session duration
*   InGame_Purchase_USD – purchase amount

To identify unusual user and entity behavior patterns-I implemented a hybrid anomaly detection approach by combining UEBA with DBSCAN along with Prophet for time-series anomaly detection. Prophet’s decomposition of data into trend, seasonality, holidays, and noise makes the model more robust to missing data and outliers compared to traditional methods like ARIMA and SARIMA, which are used for simpler and more stable datasets.
*   Prophet decompose dataset by adding additional components to the data like (Trend + Seasonality + Holidays + Noise). In Prophet, these four elements are the building blocks of a decomposable time series model. Instead of looking at a single complex line, Prophet breaks our data down into these distinct, interpretable layers and adds them together.
Unlike ARIMA (which looks at the immediate previous data point to guess the next one), Prophet looks at the entire history to map out these four layers. This makes it much more robust if you have missing data or big outliers, because a single bad day won't break the "Trend" or "Seasonality" layers.

*   We use ARIMA for simple, non-seasonal data.
*   We use SARIMA when data is stable, regular, and We need a high-precision, traditional model.

*   Trend :This is the long of-term direction of your data.
*   Seasonality :This represents periodic changes that repeat over a set timeframe

*   This handles specific dates that cause predictable, but non-periodic, shocks.

I will import following libraries for my system


*   Pandas- Handling data
*   StandardScaler from Scikit-learn library for Standardization or Z-score normalization
*   DBSCAN- form Scikit-learn library
*   Prophet an OpenSource library
*   matplotlib library for ploting the graph of Prophet for time-based anomaly detection
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import DBSCAN
from prophet import Prophet
import matplotlib.pyplot as plt

"""I will prefrom data pre-processing before I  train the model

1. Data Loading
"""

df = pd.read_csv("gaming_security_dataset.csv")

"""2. Exploratory Data Analysis (EDA)"""

print(df.head())

print(df.info())

print(df.describe())

"""As I can see that timestamp series as n object I need to convert the Timestamp column into a datetime format so that I can perform time-based analysis."""

df['Timestamp'] = pd.to_datetime(df['Timestamp'])

"""3. Feature Engineering


*   I create new features from the timestamp, such as login hour and day. I also convert categorical values into numeric format.
*   Machine learning models require numeric data



"""

df['Hour'] = df['Timestamp'].dt.hour
df['Day'] = df['Timestamp'].dt.date
df['Login_Success'] = df['Login_Success'].map({'Yes': 1, 'No': 0})

"""4. UEBA – User Behavior Baselines (User and Entity Behavior Analytics)


*   I calculate the average (Mean) behavior of each user to establish a baseline.
calculating the mean and standard deviation we build a   Baseline for the system that what is normal for a specific user.
*   The mean represents the user’s average behavior


*   Standard deviation tells the system how much a user’s behavior varies day-to-day.
*   Low Deviation: The user is very consistent -they always log in between 8:55 and 9:05 AM.


*   High Deviation: The user is unpredictable-they log in anytime between 7:00 AM and 12:00 PM
*   In UEBA, the mean and deviation are used to calculate a Z-Score, which tells the system exactly how weird  an event is. That Z-Score is then converted into a Risk Score (usually 0 to 100).















"""

user_baseline = df.groupby('UserID').agg({
    'Session_Duration_Min': 'mean',
    'InGame_Purchase_USD': 'mean',
    'Failed_Attempts': 'mean',
    'Hour': 'mean'
}).rename(columns={
    'Session_Duration_Min': 'Avg_Session',
    'InGame_Purchase_USD': 'Avg_Purchase',
    'Failed_Attempts': 'Avg_Failed',
    'Hour': 'Avg_Login_Hour'
})

df = df.merge(user_baseline, on='UserID', how='left')

user_baseline

"""5. Feature Transformation (Deviation Calculation)


*   This step calculates how much each activity deviates from the user’s normal behavior.


"""

df['Session_Dev'] = abs(df['Session_Duration_Min'] - df['Avg_Session'])
df['Purchase_Dev'] = abs(df['InGame_Purchase_USD'] - df['Avg_Purchase'])
df['Failed_Dev'] = abs(df['Failed_Attempts'] - df['Avg_Failed'])
df['LoginTime_Dev'] = abs(df['Hour'] - df['Avg_Login_Hour'])

df

"""6. Data Preprocessing


*  I normalize the data so that all features are on the same scale.


*   we used StandardScaler() from sklearn which performs a specific type of normalization called Standardization (also known as Z-score normalization).
Instead of squashing data between 0 and 1, it centers everything around zero.




"""

features = [
    'Session_Duration_Min',
    'InGame_Purchase_USD',
    'Failed_Attempts',
    'Hour',
    'Session_Dev',
    'Purchase_Dev',
    'Failed_Dev',
    'LoginTime_Dev'
]

X = df[features]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled

"""7. Machine Learning – DBSCAN (Density-Based Spatial Clustering of Applications with Noise)

*   DBSCAN is distance-based model

*   Scaling prevents one feature from dominating others

*   DBSCAN groups similar data points and marks outliers as anomalies.


*   To detect unknown attack patterns

*   No labeled data required (unsupervised learning)







"""

dbscan = DBSCAN(eps=1.5, min_samples=3)
df['Cluster'] = dbscan.fit_predict(X_scaled)
df['DBSCAN_Anomaly'] = df['Cluster'] == -1

"""8. Risk Scoring (UEBA)

*   I assign a numerical score representing how risky each activity is.
*  Helps prioritize alerts

*  I in this formula I identify why is acting weird , I prioritizing purchase, compares them to everything else, and gives them a Final Risk Grade from 0 (Safe) to 100 (Dangerous).





"""

df['Risk_Score'] = (
    df['Session_Dev'] * 0.2 +
    df['Purchase_Dev'] * 0.4 +
    df['Failed_Dev'] * 0.2 +
    df['LoginTime_Dev'] * 0.2
)

df['Risk_Score'] = 100 * (df['Risk_Score'] - df['Risk_Score'].min()) / \
                  (df['Risk_Score'].max() - df['Risk_Score'].min())

"""9. Time Series Modeling (Prophet)


*   It is Facebook/Meta model
It automatically handles:


*   trends

*   seasonality

*   holidays

*   Noise












"""

ts = df.groupby('Day').size().reset_index(name='y')
ts.columns = ['ds', 'y']
ts['ds'] = pd.to_datetime(ts['ds'])

model = Prophet()
model.fit(ts)

future = model.make_future_dataframe(periods=3)
forecast = model.predict(future)

"""Time Series Visualization"""

plt.figure()
plt.plot(ts['ds'], ts['y'], marker='o')
plt.title("Daily Login Counts")
plt.xlabel("Date")
plt.ylabel("Login Count")
plt.show()

model.plot(forecast)
plt.show()

"""Forecast output from Prophet, and it has a few key parts:

1. Blue Line (Forecast / Trend)

The solid blue line shows the model’s predicted values (yhat) over time.

In your case, it starts around ~1.0, gradually increases to ~1.6, and then drops toward the end.This represents the trend Prophet learned from our historical data.
2. Shaded Area (Uncertainty Interval)

The light blue shaded region around the line is the confidence interval (yhat_lower and yhat_upper).

A wider band = more uncertainty
A narrower band = higher confidence
You can see it gets wider in the future → this is normal because predictions become less certain over time.
3. Black Dots (Actual Observations)

The black points are your real data values.

When they fall close to the blue line → the model is accurate
When they fall far away → potential anomalies
4. Anomalies / Outliers
The point around early February (~3.0) is far above the prediction band → clear anomaly
Another point (~2.0 in March) is also higher than expected
Points below or outside the shaded region are considered unusual behavior
5. What This Means Overall
The model learned a slight upward trend over time
Most values stay around 1.0–1.6, which is your “normal behavior”
Sudden spikes (like 3.0) are detected anomalies
The drop at the end suggests either:
a real change in behavior, or
limited future data causing uncertainty

10. Post-Processing

11. Alert Generation


*  I combine multiple detection methods, and if any one flags an issue → it becomes a final alert.

12. Output / Reporting
"""

print("🚨 SECURITY ALERTS")
print(alerts[['UserID', 'Timestamp', 'Risk_Score', 'Cluster']])

"""The security analysis identified several suspicious activities across user accounts.

The most critical case is User U10231, which shows very high risk scores and multiple anomalies, indicating a likely account takeover attack followed by suspicious activity.

A group of users (U44556–U44558) exhibited rapid login attempts within a short time window, suggesting a credential stuffing or bot attack, although this was not strongly flagged by the risk model.

Other users (U22334, U55667, U99001) were identified as anomalies by the clustering model but had low risk scores, indicating potential false positives or minor behavioral deviations.

Overall, the system successfully detected major threats but could be improved by adding rule-based detection for automated attacks.
"""